# Generated by Django 4.2.7 on 2023-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_choice',
            field=models.CharField(choices=[('news', 'новость'), ('content', 'статья')], default='content', max_length=7),
        ),
    ]
